name: Deploy Infra and Lambda

on:
  push:
    branches:
      - main

env:
  BUCKET_NAME: "lambda-code-acompanhamento"

jobs:
  setup_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Instalar dependências e criar pacotes ZIP
        run: |
          mkdir -p build
          pip install -r requirements.txt --platform manylinux2014_x86_64 --target build/ --only-binary=:all:
          if [ ! -d "app" ]; then
            echo "Diretório 'app/' não encontrado!"
            exit 1
          fi
          cp -r app/ build/
          cd build
          zip -r ../lambda-api.zip .
          zip -r ../lambda-sqs.zip .
          cd ..

      - name: Salvar pacotes ZIP como artefatos
        uses: actions/upload-artifact@v3
        with:
          name: lambda-api.zip
          path: lambda-api.zip

      - name: Salvar pacote SQS ZIP como artefato
        uses: actions/upload-artifact@v3
        with:
          name: lambda-sqs.zip
          path: lambda-sqs.zip

  upload_to_s3:
    needs: setup_and_build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Baixar pacotes ZIP
        uses: actions/download-artifact@v3
        with:
          name: lambda-api.zip
          path: .
        env:
          ACTIONS_STEP_DEBUG: true

      - name: Baixar pacote SQS ZIP
        uses: actions/download-artifact@v3
        with:
          name: lambda-sqs.zip
          path: .
        env:
          ACTIONS_STEP_DEBUG: true

      - name: Verificar arquivos ZIP
        run: |
          ls -l
          if [ ! -f "lambda-api.zip" ]; then
            echo "Arquivo lambda-api.zip não encontrado!"
            exit 1
          fi
          if [ ! -f "lambda-sqs.zip" ]; then
            echo "Arquivo lambda-sqs.zip não encontrado!"
            exit 1
          fi

      - name: Instalar AWS CLI
        run: |
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Criar bucket S3 e enviar arquivos ZIP
        run: |
          aws configure set cli_pager ""          
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
          aws s3api create-bucket --bucket $BUCKET_NAME --region us-east-1
          aws s3 cp lambda-api.zip s3://$BUCKET_NAME/lambda-api.zip
          aws s3 cp lambda-sqs.zip s3://$BUCKET_NAME/lambda-sqs.zip
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }}

  terraform_apply:
    needs: upload_to_s3
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install terraform

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init -input=false -backend-config="bucket=techchallangebucket" -backend-config="key=hackaton.tfstate" -backend-config="region=us-east-1"

      - name: Baixar artefatos para o Terraform
        uses: actions/download-artifact@v3
        with:
          name: lambda-api.zip
          path: ./terraform/

      - name: Baixar artefatos para o Terraform
        uses: actions/download-artifact@v3
        with:
          name: lambda-sqs.zip
          path: ./terraform/

      - name: Plan Terraform changes
        working-directory: ./terraform
        run: terraform plan -input=false -out=tfplan

      - name: Apply Terraform changes
        working-directory: ./terraform
        run: terraform apply -input=false -auto-approve tfplan
