name: Deploy Lambda

on:
  push:
    branches:
      - 'main'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_DEFAULT_REGION: us-east-1
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0
    
    - name: Terraform Init
      working-directory: terraform
      run: terraform init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=acompanhamento.tfstate" -backend-config="region=us-east-1"
    
    - name: Apply Terraform
      working-directory: terraform
      run: terraform apply -input=false -auto-approve 