name: Deploy Infra and Lambda

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Configuração do ambiente e construção dos pacotes
  setup_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Instalar dependências e criar pacotes ZIP
        run: |
          # Criar diretório para Lambda API
          mkdir -p build_api
          if [ ! -f "requirements.txt" ]; then
            echo "Arquivo requirements.txt não encontrado."
            exit 1
          fi
          pip install -r requirements.txt --platform manylinux2014_x86_64 --target build_api/ --only-binary=:all:
          cp -r app/api/* build_api/
          cd build_api
          zip -r ../lambda-api.zip .
          cd ..

          # Criar diretório para Lambda SQS
          mkdir -p build_sqs
          if [ ! -f "requirements.txt" ]; then
            echo "Arquivo requirements.txt não encontrado."
            exit 1
          fi
          pip install -r requirements.txt --platform manylinux2014_x86_64 --target build_sqs/ --only-binary=:all:
          cp -r app/sqs/* build_sqs/
          cd build_sqs
          zip -r ../lambda-sqs.zip .
          cd ..

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Salvar pacotes ZIP como artefatos
        uses: actions/upload-artifact@v3
        with:
          name: lambda-api.zip
          path: lambda-api.zip

      - name: Salvar pacote SQS ZIP como artefato
        uses: actions/upload-artifact@v3
        with:
          name: lambda-sqs.zip
          path: lambda-sqs.zip

  # Job 2: Criar o bucket S3 e enviar os arquivos ZIP
  upload_to_s3:
    needs: setup_and_build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Baixar pacotes ZIP
        uses: actions/download-artifact@v3
        with:
          name: lambda-api.zip
          path: .

      - name: Baixar pacote SQS ZIP
        uses: actions/download-artifact@v3
        with:
          name: lambda-sqs.zip
          path: .

      - name: Criar bucket S3 e enviar arquivos ZIP
        run: |
          BUCKET_NAME="lambda-code-acompanhamento"
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
          aws s3api create-bucket --bucket $BUCKET_NAME --region us-east-1
          aws s3 cp lambda-api.zip s3://$BUCKET_NAME/lambda-api.zip
          aws s3 cp lambda-sqs.zip s3://$BUCKET_NAME/lambda-sqs.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

  # Job 3: Aplicação do Terraform
  terraform_apply:
    needs: upload_to_s3
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Inicializar o Terraform
        run: |
          cd terraform
          terraform init -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}" \
                         -backend-config="key=terraform/state/hackaton.tfstate" \
                         -backend-config="region=us-east-1" \
                         -backend-config="encrypt=false"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Aplicar configuração Terraform
        run: |
          cd terraform
          terraform apply -auto-approve -var "s3_bucket_name=$BUCKET_NAME"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
